### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by Dragonk**
Update Polish translation.

### CODE REVIEW

**Comment by nobodyknowsmyname** [comment]
Download string file and translate yourself. Then push to GitHub

**Comment by AmulyaX** [comment]
Sorry I accidentally closed it.

**Comment by AmulyaX** [comment]
> Download string file and translate yourself. Then push to GitHub

What?

**Comment by AmulyaX** [comment]
> Update Polish translation.

Thanks a lot for the contribution.

**Pull request merged**
